import Head from "next/head";
import { BsGithub } from "react-icons/bs";
import Dashboard from "../components/Dashboard";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Khayangan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Dashboard />
      </main>

      <footer></footer>
    </div>
  );
}
