import Head from "next/head";
import { BsGithub } from "react-icons/bs";
import Dashboard from "../components/Dashboard";
import DetailProjecct from "../components/Detail";
import Nav from "../components/Nav";
import NewProject from "../components/New";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Khayangan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav />
        <DetailProjecct />
      </main>

      <footer></footer>
    </div>
  );
}
