import Head from "next/head";
import NewProject from "../components/NewProject";
import Dashboard from "../components/Dashboard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NewProject />
      </main>

      <footer></footer>
    </div>
  );
}
